name = "supabase-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Variables d'environnement
[env.production.vars]
SUPABASE_URL = "https://tjrrdcdokahdsatfhaqq.supabase.co"

# Secrets (à définir avec wrangler secret put)
# SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcnJkY2Rva2FoZHNhdGZoYXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTMyODYsImV4cCI6MjA2ODY2OTI4Nn0.M4Reaf5dUz8x6M2LJcRoi6SDuhXb1DRJA8TvQSHAnh0"

# KV Namespaces
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your_cache_kv_namespace_id"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "your_rate_limit_kv_namespace_id"

# Custom domain (optionnel)
[env.production]
routes = [
  { pattern = "api.yourapp.com/*", custom_domain = true }
]

# Développement local
[env.development.vars]
SUPABASE_URL = "http://localhost:54321"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "dev_cache_kv_namespace_id"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT"
id = "dev_rate_limit_kv_namespace_id"